export default {
  ADD: "ADD FRIEND",
  REM: "UNFRIEND",
  CANCEL: "CANCEL REQUEST",
  CHECK_ADDED: "CHECK IF ADDED",
  CHECK_FRIENDS: "CHECK IF FRIENDS",
  PENDING: "PENDING",
  EDIT: "EDIT",
  ACCEPT: "ACCEPT",
  DENIE: "DENIE",
};
